### ISSUE TITLE
Force HTTPS

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirruslabs.github.io#4]
Force HTTPS in settings should be enabled.  Studies show it improves user confidence in the product.

**Comment by fkorotkov** [comment]
Enabled. Thanks for noticing.

**Comment by RDIL** [comment]
Btw I think you forgot to respond to me on Twitter...

**Comment by fkorotkov** [comment]
I have not. It's just not a short response which I need to compile. I'm at a conference at the moment and time is limited.

**Comment by RDIL** [comment]
Oh okay sorry
